# Generated by Django 5.1.7 on 2025-03-15 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('loja', '0004_products_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='phones',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='products',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
    ]
